sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Np8zO+W+KSdDL2OHQU4hraPpJQGaRWWdYT8wPxmJyrdtPuYnPLnC+ycw+XFJ49X9ZE6DsYpsDOAYxG4WlimzHsHgKfbVioNcDsKB5Kf7eTT8XV7O9yiS1HDw/kQFhA3Z1QtJgyoc3v79mmZq/qL0a9MEtn7EJBP/7aKR1o9MwCyimaSExJlH0glIoOCzQSaCMjLXUtMKZnNEklQYmjjBOXVfix9HbUOyaMDglbELYe06RX8a8c3G28dX25YCOVFz10JDgEZAE/Vg9xh08VMEONcnQTIW0ZOdbJIkmmbBYag1nOp1mcN6e0XFH+JE1KkYaSctIpmeUV4tS8VSUhN/PRKMmiVGiX4VniSw7kDlLTWZ8NsoMat1mOs/IPBC2o0LQxDAcWR7vp3nWNfMPgzSTZpMZ+2S42SR3kAkrfZn8fpGxdda2DXXR6hfUbAXCRYYq6Fyfz4vKXmLZ8lw9ufuLcHVUuJVYyKidYSCd1BckJlqDH7AxY7RUB/NPTHghaAzTuUyGMITGKZoGic0qfAj0dqOSUc5DfL22S4VniEhJ6Gk8lxzCOKRnJvYRJ0ERIsut9+xyB0ZS28/8UOvdxmNhz9jc2pFK2b9GPW07xnxS17C4cqMWiU2wajuEz1uKSi43+d7cG9dX90zsRfF5+AdF1kMVn1QmReg/p2KV7L91dY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Starr-King-in-California_4641
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy